// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJHXCM9WQv8qDfzUNTNVs2DY_S7g-vwWc',
    appId: '1:842788466977:android:6d8af0adc47cb80530ce60',
    messagingSenderId: '842788466977',
    projectId: 'flutternoteapp-9a952',
    storageBucket: 'flutternoteapp-9a952.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzeDVDItoJ6XyRBWWl5SFFughdkDFvpp4',
    appId: '1:842788466977:ios:9f66a61a59f6bd6c30ce60',
    messagingSenderId: '842788466977',
    projectId: 'flutternoteapp-9a952',
    storageBucket: 'flutternoteapp-9a952.firebasestorage.app',
    iosBundleId: 'com.noteapp.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaZJfuRMERQSC3VIYDjJDd-reD22cQZzE',
    appId: '1:842788466977:web:62b735dafbad761f30ce60',
    messagingSenderId: '842788466977',
    projectId: 'flutternoteapp-9a952',
    authDomain: 'flutternoteapp-9a952.firebaseapp.com',
    storageBucket: 'flutternoteapp-9a952.firebasestorage.app',
    measurementId: 'G-THQGBGTXFK',
  );
}
